name: "Build app"

on:
  workflow_dispatch:


run-name: app.build [${{ github.ref_name }}] @${{ github.actor }}

env:
  REGISTRY_OWNER: kokuryio
  REGISTRY_URL: ghcr.io
  IMAGE_TAG: thb-sharing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        shell: bash
        run: echo "${{ secrets.REGISTRY_PAT }}" | docker login ghcr.io -u ${{ env.REGISTRY_OWNER }} --password-stdin

      - name: Build Docker image
        shell: bash
        run: |
          cd "${{ github.workspace }}"
          docker build -t ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_OWNER }}/${{ env.IMAGE_TAG }}:latest .

      - name: Push image to registry
        shell: bash
        run: |
          docker push ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_OWNER }}/${{ env.IMAGE_TAG }}:latest

      - name: Wait for registry consistency
        run: sleep 10

      - name: Trigger Azure Webhook with PowerShell
        shell: pwsh
        run: |
          Invoke-RestMethod -Method Post -Uri "${{ secrets.AZURE_WEBHOOK_URL }}"
